extends:
  - airbnb-base
  - plugin:jest/recommended
rules:
  eqeqeq: 0
  no-await-in-loop: 0
  no-restricted-syntax: 0
  no-plusplus: 0
  arrow-body-style: ["error", "as-needed", { "requireReturnForObjectLiteral": true }]
  no-underscore-dangle: 0
  comma-dangle: ["error", "always-multiline"]
  no-mixed-spaces-and-tabs: ["error", "smart-tabs"]
  object-shorthand: ["error", "always", { "avoidExplicitReturnArrows": true, "ignoreConstructors": true }]
  max-len: ["error", { "code": 150 }]
  no-use-before-define: ["error", { "functions": false }]
  import/no-extraneous-dependencies: ["error", { "devDependencies": true }]
  linebreak-style: 0
